// SPDX-License-Identifier: GPL-2.0
pragma solidity ^0.8.0;

// Chimera deps
import {BaseSetup} from "@chimera/BaseSetup.sol";
import {vm} from "@chimera/Hevm.sol";

// Managers
import {ActorManager} from "@recon/ActorManager.sol";
import {AssetManager} from "@recon/AssetManager.sol";

// Helpers
import {Utils} from "@recon/Utils.sol";

// Your deps
import "src/BribeInitiative.sol";
import "src/CurveV2GaugeRewards.sol";
import "src/Governance.sol";
import "src/UniV4MerklRewards.sol";
import {IGovernance} from "src/interfaces/IGovernance.sol";
import {IBribeInitiative} from "src/interfaces/IBribeInitiative.sol";
import {IERC20} from "openzeppelin/contracts/interfaces/IERC20.sol";
import {ILiquidityGauge} from "src/interfaces/ILiquidityGauge.sol";
import {PermitParams} from "src/utils/Types.sol";

// Mocks
import {MockERC20Tester} from "../mocks/MockERC20Tester.sol";
import {MockStakingV1} from "../mocks/MockStakingV1.sol";
import {MockLiquidityGauge} from "../mocks/MockLiquidityGauge.sol";
import {MockDistributionCreator} from "../mocks/MockDistributionCreator.sol";
import {MockUniV4MerklRewards} from "../mocks/MockUniV4MerklRewards.sol";

abstract contract Setup is BaseSetup, ActorManager, AssetManager, Utils {
    // === ARCHITECTURE NOTES === //
    // @audit chose moderate setup because the system has clear core contracts (Governance, 1 BribeInitiative) that must exist, but benefits from fuzzer-controlled deployment of additional initiatives
    // @audit NOT TESTING: Multiple Governance instances - architecturally nonsensical, Governance is a singleton coordinator
    // @audit NOT TESTING: CurveV2GaugeRewards and UniV4MerklRewards in initial setup - these are optional reward distribution mechanisms that can be deployed via helpers if fuzzer explores those paths
    // @audit NOT TESTING: Complex V1 staking migration scenarios with ETH gains - MockStakingV1 provides basic stake/unstake but complex V1 migration is out of scope
    // @audit NOT TESTING: More than 2 actors - system supports arbitrary users but 2 actors (address(this) + 1 additional) is sufficient to test multi-user interactions while keeping state space manageable
    // @audit ASSUMPTION: Using START_TIME and EPOCH_DURATION constants from existing setup - these match the deployment test values
    // @audit ASSUMPTION: BribeInitiative deployed in setup uses a generic bribeToken - fuzzer can deploy additional BribeInitiatives with different tokens via helper
    // @audit ASSUMPTION: All struct parameters use single mode because they're either generated by helpers (_getValidPermitParams) or read from governance state - fuzzer doesn't need to generate these complex structs
    // @audit UNCERTAINTY: Whether to track ETH rewards from V1 staking - MockStakingV1 supports it but adds complexity. Keeping it for completeness.
    // @audit chose to NOT deploy UserProxy in setup because governance auto-deploys it on first stake via _increaseUserVoteTrackers(). Storing the address after first deployment for convenience.
    // @audit chose needs_private_key=true because depositLQTYViaPermit requires valid EIP-2612 signatures. Using hardcoded actor 0x537C8f3d3E18dF5517a58B3fB9D9143697996802 with known private key.
    // @audit Trade-off: Deploying only 1 BribeInitiative in setup vs 0 - chose 1 because most tests will use BribeInitiative and it's the primary initiative type. Helpers allow deploying more.
    // @audit Trade-off: Using MockERC20Tester vs standard MockERC20 - chose MockERC20Tester because it has permit() functionality needed for depositLQTYViaPermit testing
    // @audit Coverage gap: Not testing initiative hook gas limits (MIN_GAS_TO_HOOK) - this is a security feature but difficult to test in fuzzing without custom malicious initiatives
    // @audit Coverage gap: Not testing registration/unregistration edge cases around UNREGISTRATION_AFTER_EPOCHS - these require precise epoch timing that may be hard for fuzzer to hit
    // @audit Design choice: Storing struct parameters in Setup rather than having fuzzer generate them - this simplifies fuzzing since these structs are either derived from contract state or require complex signature generation

    // Constants
    uint256 internal constant DECIMALS = 18;
    uint32 internal constant START_TIME = 1732873631;
    uint32 internal constant EPOCH_DURATION = 7 days;
    uint128 internal constant REGISTRATION_FEE = 1 ether;

    // Singleton contracts (required for system to start)
    Governance internal governance;
    
    // Primary BribeInitiative reference (for convenience - points to first deployed)
    BribeInitiative internal bribeInitiative;

    // Token contracts
    MockERC20Tester internal lqty;
    MockERC20Tester internal lusd;
    MockERC20Tester internal bold;
    MockERC20Tester internal bribeToken;

    // Infrastructure contracts
    MockStakingV1 internal stakingV1;
    MockLiquidityGauge internal mockLiquidityGauge;
    MockDistributionCreator internal mockDistributionCreator;

    // Multi-instance contract arrays (for contracts with helper_deploy)
    address[] internal deployedBribeInitiatives;
    address[] internal deployedCurveV2GaugeRewards;
    address[] internal deployedUniV4MerklRewards;

    // Proxy deployment
    address internal userProxy;

    // Private key for permit testing
    uint256 internal userPrivateKey =
        23868421370328131711506074113045611601786642648093516849953535378706721142721;

    // Struct parameters (single mode)
    PermitParams internal permitParams;
    IBribeInitiative.ClaimData internal claimData;
    IGovernance.UserState internal userState;
    IGovernance.Allocation internal allocation;
    IGovernance.InitiativeState internal initiativeState;

    /// === Setup === ///
    /// This contains all calls to be performed in the tester constructor, both for Echidna and Foundry
    function setup() internal virtual override {
        // 1. Time warp to START_TIME for epoch-based testing
        vm.warp(START_TIME);

        // 2. Add additional actor with known private key for permit testing
        _addActor(0x537C8f3d3E18dF5517a58B3fB9D9143697996802);

        // 3. Deploy tokens (not using AssetManager since these have fixed roles)
        lqty = new MockERC20Tester("LQTY", "LQTY");
        lusd = new MockERC20Tester("LUSD", "LUSD");
        bold = new MockERC20Tester("BOLD Stablecoin", "BOLD");
        bribeToken = new MockERC20Tester("Bribe Token", "BRIBE");

        // 4. Deploy infrastructure mocks
        stakingV1 = new MockStakingV1(lqty, lusd);
        mockLiquidityGauge = new MockLiquidityGauge(address(bold));
        mockDistributionCreator = new MockDistributionCreator();

        // Allow stakingV1 to spend LQTY without approval (matches real LQTYStaking behavior)
        lqty.mock_setWildcardSpender(address(stakingV1), true);

        // 5. Deploy Governance (singleton - required for system to start)
        IGovernance.Configuration memory config = IGovernance.Configuration({
            registrationFee: REGISTRATION_FEE,
            registrationThresholdFactor: 0.01 ether,
            unregistrationThresholdFactor: 4 ether,
            unregistrationAfterEpochs: 4,
            votingThresholdFactor: 0.04 ether,
            minClaim: 0,
            minAccrual: 0,
            epochStart: START_TIME - EPOCH_DURATION,
            epochDuration: EPOCH_DURATION,
            epochVotingCutoff: EPOCH_DURATION - 1 days
        });

        address[] memory initialInitiatives = new address[](0);
        governance = new Governance(
            address(lqty),
            address(lusd),
            address(stakingV1),
            address(bold),
            config,
            address(this),
            initialInitiatives
        );

        // 6. Deploy 1 BribeInitiative in setup for basic testing
        bribeInitiative = new BribeInitiative(
            address(governance),
            address(bold),
            address(bribeToken)
        );
        deployedBribeInitiatives.push(address(bribeInitiative));

        // 7. Mint initial tokens to actors
        uint256 initialAmount = type(uint88).max;
        address[] memory actors = _getActors();
        for (uint256 i = 0; i < actors.length; i++) {
            lqty.mint(actors[i], initialAmount);
            lusd.mint(actors[i], initialAmount);
            bold.mint(actors[i], initialAmount);
            bribeToken.mint(actors[i], initialAmount);
        }

        // 8. Mint BOLD to governance for reward distribution
        bold.mint(address(governance), initialAmount);

        // 9. Set up approvals array for all relevant contracts
        address[] memory approvalArray = new address[](3);
        approvalArray[0] = address(stakingV1);
        approvalArray[1] = address(governance);
        approvalArray[2] = address(bribeInitiative);

        // 10. Finalize asset deployment (approve all tokens from actors to contracts)
        // Note: For UserProxy approvals, users must approve governance.deriveUserProxyAddress(user)
        // before calling depositLQTY, or use depositLQTYViaPermit instead
        _finalizeAssetDeployment(_getActors(), approvalArray, type(uint88).max);
    }

    /// === Helper Deploy Functions (fuzzer-controlled deployment) === ///

    /// @notice Deploy a new BribeInitiative with a custom bribe token
    /// @param bribeTokenAddress Address of the bribe token for this initiative
    function helper_deployBribeInitiative(address bribeTokenAddress) public {
        address instance = address(new BribeInitiative(
            address(governance),
            address(bold),
            bribeTokenAddress
        ));
        deployedBribeInitiatives.push(instance);
    }

    /// @notice Deploy a new CurveV2GaugeRewards with custom gauge and duration
    /// @param bribeTokenAddress Address of the bribe token
    /// @param gaugeAddress Address of the liquidity gauge
    /// @param duration Duration for reward distribution
    function helper_deployCurveV2GaugeRewards(address bribeTokenAddress, address gaugeAddress, uint256 duration) public {
        address instance = address(new CurveV2GaugeRewards(
            address(governance),
            address(bold),
            bribeTokenAddress,
            gaugeAddress,
            duration
        ));
        deployedCurveV2GaugeRewards.push(instance);
    }

    /// @notice Deploy a new UniV4MerklRewards with custom configuration
    /// @param campaignBoldAmountThreshold Minimum BOLD amount threshold for campaigns
    /// @param uniV4PoolId Uniswap V4 pool ID
    /// @param weightFees Weight for fees
    /// @param weightToken0 Weight for token0
    /// @param weightToken1 Weight for token1
    function helper_deployUniV4MerklRewards(
        uint256 campaignBoldAmountThreshold,
        bytes32 uniV4PoolId,
        uint32 weightFees,
        uint32 weightToken0,
        uint32 weightToken1
    ) public {
        address instance = address(new MockUniV4MerklRewards(
            address(governance),
            address(bold),
            campaignBoldAmountThreshold,
            uniV4PoolId,
            weightFees,
            weightToken0,
            weightToken1,
            address(mockDistributionCreator)
        ));
        deployedUniV4MerklRewards.push(instance);
    }

    /// === Instance Getters === ///

    /// @notice Get a deployed BribeInitiative by index
    /// @param index Index to select from deployedBribeInitiatives array
    /// @return address of the selected BribeInitiative
    function _getDeployedBribeInitiative(uint8 index) internal view returns (address) {
        require(deployedBribeInitiatives.length > 0, "No BribeInitiatives deployed");
        return deployedBribeInitiatives[index % deployedBribeInitiatives.length];
    }

    /// @notice Get a deployed CurveV2GaugeRewards by index
    /// @param index Index to select from deployedCurveV2GaugeRewards array
    /// @return address of the selected CurveV2GaugeRewards
    function _getDeployedCurveV2GaugeRewards(uint8 index) internal view returns (address) {
        require(deployedCurveV2GaugeRewards.length > 0, "No CurveV2GaugeRewards deployed");
        return deployedCurveV2GaugeRewards[index % deployedCurveV2GaugeRewards.length];
    }

    /// @notice Get a deployed UniV4MerklRewards by index
    /// @param index Index to select from deployedUniV4MerklRewards array
    /// @return address of the selected UniV4MerklRewards
    function _getDeployedUniV4MerklRewards(uint8 index) internal view returns (address) {
        require(deployedUniV4MerklRewards.length > 0, "No UniV4MerklRewards deployed");
        return deployedUniV4MerklRewards[index % deployedUniV4MerklRewards.length];
    }

    /// === Status Getters === ///

    /// @notice Get the current epoch number
    /// @return Current epoch from governance contract
    function _getCurrentEpoch() internal view returns (uint256) {
        return governance.epoch();
    }

    /// === Custom Helper Functions === ///

    /// @notice Generate valid permit parameters for EIP-2612 permit
    /// @param owner Address that owns the tokens
    /// @param spender Address that will spend the tokens
    /// @param value Amount of tokens to permit
    /// @param deadline Permit expiration timestamp
    /// @return Valid PermitParams struct with signature
    function _getValidPermitParams(
        address owner,
        address spender,
        uint256 value,
        uint256 deadline
    ) internal returns (PermitParams memory) {
        // Create the permit digest
        bytes32 permitTypeHash = keccak256(
            "Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)"
        );
        bytes32 domainSeparator = lqty.DOMAIN_SEPARATOR();
        uint256 nonce = lqty.nonces(owner);

        bytes32 structHash = keccak256(
            abi.encode(permitTypeHash, owner, spender, value, nonce, deadline)
        );
        bytes32 digest = keccak256(
            abi.encodePacked("\x19\x01", domainSeparator, structHash)
        );

        // Sign with the known private key
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(userPrivateKey, digest);

        return
            PermitParams({
                owner: owner,
                spender: spender,
                value: value,
                deadline: deadline,
                v: v,
                r: r,
                s: s
            });
    }

    /// === MODIFIERS === ///

    modifier asAdmin() {
        vm.prank(address(this));
        _;
    }

    modifier asActor() {
        vm.prank(address(_getActor()));
        _;
    }
}
